blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/yusei36/FluentPassFinder/blob/master/README.md
    about: Read the documentation before opening an issue
